### PR TITLE
Less temp strings in RemoteClientProcess#read_bytes

### PR DESCRIPTION
**Pull request by stulentsev**
String#<< is much more efficient than String#+

### CODE REVIEW

**Comment by stulentsev** [comment]
Addresses the issue from https://github.com/Russian-AI-Cup-2017/cpp-cgdk/pull/4#issuecomment-348195368

**Comment by SladeThe** [comment]
Accepted pull request as a part of bigger (not big) update. However, it doesn't make any change in terms of performance, when tested on our servers.

**Comment by stulentsev** [comment]
@SladeThe 

> it doesn't make any change in terms of performance, when tested on our servers.

Interestingly enough, local profiling showed insignificant differences too. BUT! without it I was timing out 80% of the time. And with it - maybe 10-20%. Same code. That's enough evidence for me. :)

> Accepted pull request 

I don't see this change in master yet, though. 🤷‍♂️

**Comment by SladeThe** [comment]
Pushed.

**Pull request closed without merging**
